// Generated using Sourcery 0.15.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT


//: Do not change this code as it is autogenerated every time you build.
//: You can change the code in `../StencilTemplatesForSourcery/Application/AutoGenerateProtocol
import Foundation

// MARK: - AutoGenerateProtocol
//: From all Types implementing this protocol Sourcery adds:
//: - public/internal variables // private variables are ignored
//: - public/internal methods (skips initializers)
//: - initializers marked with annotation // sourcery:includeInitInProtocol
//: - of the above it does not add it if  // sourcery:skipProtocol
//: ---





// Generated protocol inline for SystemExecutableProvider -> See code in the file of that type
    // sourcery:inline:SystemExecutableProvider.AutoGenerateProtocol
    static var shared: SystemExecutableProviderProtocol { get }
    var pathEnvironmentParser: PathEnvironmentParserProtocol { get }
    var fileSystem: FileSystemProtocol { get }

    func executable(with executableName: String) throws  -> FileProtocol
    // sourcery:end
// Generated protocol inline for Task -> See code in the file of that type
    // sourcery:inline:Task.AutoGenerateProtocol
    var name: String { get }
    var executable: FileProtocol { get set }
    var arguments: Arguments { get set }
    var input: Channel { get set }
    var output: Channel { get set }
    var capturedOutputData: Data? { get }
    var readOutputString: String? { get }
    var trimmedOutput: String? { get }
    var capturedOutputString: String? { get }
    var toProcess: Process { get }
    var description: String { get }

    func enableReadableOutputDataCapturing()
    // sourcery:end
// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

// Generated protocol inline for  -> See code in the file of that type

