sources:
- "/Users/doozmen/Documents/dooz/Open/highway/Sources/"
- "/Users/doozmen/Documents/dooz/Open/highway/Sources/🧙‍♂️/AutoProtocols/SourceryAutoProtocols.swift"
templates:
- "/Users/doozmen/Documents/dooz/Open/highway/Carthage/Checkouts/template-sourcery/sources/stencil"
output:
 "/Users/doozmen/Documents/dooz/Open/highway/Sources/🧙‍♂️/Mocks/"