sources:
- "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/Sources/GitHooksLibrary/"
- "AutoMockable filled value"

templates:
- "AutoMockable filled value"
output:
 "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/Sources/Generated/GitHooksLibrary/"