sources:
- "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/Sources/DocumentationLibrary/"
- "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/.build/checkouts/template-sourcery-2823880972965882016/Sources/SourceryAutoProtocols/SourceryAutoProtocols.swift"

templates:
- "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/.build/checkouts/template-sourcery-2823880972965882016/"
output:
 "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/Sources/Generated/DocumentationLibrary/"