sources:
- "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/Sources/HighwayTests/"
- "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/.build/checkouts/template-sourcery--108890666365077616/Sources/SourceryAutoProtocols/SourceryAutoProtocols.swift"

templates:
- "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/.build/checkouts/template-sourcery--108890666365077616/"
output:
 "/Users/stijnwillems/Documents/dev.nosync/Open/Highway/Sources/Generated/HighwayTests/"