//
//  DemoSourceryWorker.swift
//  Automate
//
//  Created by Stijn on 16/12/2018.
//  Copyright © 2018 dooz. All rights reserved.
//

import Foundation
import SourceryAutoProtocols
import ZFile
import Terminal
import SourceryWorker
import SignPost

protocol DemoSourceryWorkerProtocol {
    //// sourcery:inline:DemoSourceryWorker.AutoGenerateProtocol
    
    func attempt() throws
    
    //// sourcery:end
}

struct AutomateHighwaySourceryWorker: DemoSourceryWorkerProtocol, AutoGenerateProtocol {
    
    private let signPost: SignPostProtocol
    private let workers: [SourceryWorkerProtocol]
    
    init(signPost: SignPostProtocol = SignPost.shared, workers: [SourceryWorkerProtocol]? = nil) throws {
        self.signPost = signPost
        
        guard workers == nil else {
            self.workers = workers!
            return
        }
        
        let currentFolder = FileSystem().currentFolder
        signPost.message("💁🏻‍♂️ Running in folder\n \(currentFolder)\n")
        
        var carthageFolder: FolderProtocol!
        var projectFolder: FolderProtocol!
        
        do {
            projectFolder = try currentFolder.parentFolder().parentFolder().parentFolder()
            signPost.message("💁🏻‍♂️ Project in folder\n \(projectFolder!.path)\n")
            carthageFolder = try projectFolder.subfolder(named: "Carthage")
        } catch {
            signPost.message("💁🏻‍♂️ Not running in .build.nosync/Debug folder, trying to run from current folder.")
            projectFolder = currentFolder
            carthageFolder = try currentFolder.subfolder(named: "Carthage")
        }
        
        let sourcerySequence = [
            try sourceryForFolders(target: "Arguments", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Deliver", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Errors", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Git", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Keychain", projectFolder, carthageFolder),
            try sourceryForFolders(target: "POSIX", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Result", projectFolder, carthageFolder),
            try sourceryForFolders(target: "SignPost", projectFolder, carthageFolder),
            try sourceryForFolders(target: "SourceryWorker", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Task", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Terminal", projectFolder, carthageFolder),
            try sourceryForFolders(target: "Url", projectFolder, carthageFolder),
            try sourceryForFolders(target: "XCBuild", projectFolder, carthageFolder),
        ]
        
        try sourcerySequence.forEach {
            signPost.message("""
                🧙‍♂️ Sourcery will run from config file
                > \($0.sourceryYMLFile.path)
                
                ```yml
                \(try $0.sourceryYMLFile.readAsString())
                ```
                
                """
            )
        }
        
        
        self.workers =  try sourcerySequence.map { try SourceryWorker(sourcery: $0) }
        
    }
    
    // MARK: - Sourcery Setup
    
    
    
    func attempt() throws {
        return try workers.forEach {
            let output = try $0.attempt()
            signPost.verbose("\(output.joined(separator: "\n"))")
        }
    }
}

private func sourceryForFolders(target: String, _ projectFolder: FolderProtocol, individualSourceFiles: [File]? = nil, _ carthageFolder: FolderProtocol) throws -> Sourcery {
    
    let sourcesFolder = try projectFolder.subfolder(named: "Sources")
    
    return try Sourcery(
        sourcesFolders: [sourcesFolder.subfolder(named: target)],
        individualSourceFiles: individualSourceFiles,
        templateFolder: try Folder(relativePath: "Checkouts/template-sourcery/sources/stencil", to: carthageFolder),
        outputFolder: try sourcesFolder.createSubfolderIfNeeded(withName: "AutoGeneratedCode").createSubfolderIfNeeded(withName: target),
        sourceryAutoProtocolsFile: try projectFolder.file(named: "/Sources/AutoGeneratedCode/SourceryAutoProtocols.swift"),
        sourceryYMLFile: try projectFolder.createFileIfNeeded(named: ".sourcery-\(target).yml"),
        imports: Set([
            TemplatePrepend(
                name: Set([
                    TemplatePrepend.Import(name: target, testable: false),
                    TemplatePrepend.Import(name: "SourceryAutoProtocols"),
                    TemplatePrepend.Import(name: "Foundation"),
                    TemplatePrepend.Import(name: "os"),
                    ]),
                template: "AutoMockable")
            ])
    )
    
}
