//
//  DemoSourceryWorker.swift
//  Automate
//
//  Created by Stijn on 16/12/2018.
//  Copyright © 2018 dooz. All rights reserved.
//

import Foundation
import SourceryAutoProtocols
import ZFile
import Terminal
import SourceryWorker
import SignPost

protocol DemoSourceryWorkerProtocol {
    //// sourcery:inline:DemoSourceryWorker.AutoGenerateProtocol
    
    func attempt() throws
    
    //// sourcery:end
}

struct AutomateHighwaySourceryWorker: DemoSourceryWorkerProtocol, AutoGenerateProtocol {
    
    private let signPost: SignPostProtocol
    private let workers: [SourceryWorkerProtocol]
    private static let commonImportAutoMockable = Set([
        TemplatePrepend.Import(name: "SourceryAutoProtocols"),
        TemplatePrepend.Import(name: "Foundation"),
        TemplatePrepend.Import(name: "os"),
    ])
    
    enum Target: String, CaseIterable {
        case Arguments
        case Deliver
        case Git
        case Keychain
        case SignPost
        case SourceryWorker
        case Terminal
        case Url
        case XCBuild
        case Errors
        case POSIX
        case Result
        case Task
        
        func imports() -> Set<TemplatePrepend> {
            
            // Insert the target itself
            var importNames = AutomateHighwaySourceryWorker.commonImportAutoMockable
            importNames.insert(TemplatePrepend.Import(name: self.rawValue))

            // If not the default, add a case and insert imports into importNames
            switch self {
            case .SourceryWorker:
                importNames.insert(TemplatePrepend.Import(name: VendorFramework.ZFile.rawValue))
                
                return Set([TemplatePrepend(name: importNames, template: Template.AutoMockable.rawValue)])
            case .Task:
                importNames.insert(TemplatePrepend.Import(name: Target.Arguments.rawValue))
                importNames.insert(TemplatePrepend.Import(name: VendorFramework.ZFile.rawValue))
                importNames.insert(TemplatePrepend.Import(name: Target.SignPost.rawValue))
                
                return Set([TemplatePrepend(name: importNames, template: Template.AutoMockable.rawValue)])
            case .Terminal:
                importNames.insert(TemplatePrepend.Import(name: Target.Arguments.rawValue))
                importNames.insert(TemplatePrepend.Import(name: VendorFramework.ZFile.rawValue))
                
                return Set([TemplatePrepend(name: importNames, template: Template.AutoMockable.rawValue)])
            default:
                return Set([TemplatePrepend(name: importNames, template: Template.AutoMockable.rawValue)])
            }
        }
    }
    
    enum VendorFramework: String, CaseIterable {
        case ZFile
    }
    
    enum Template: String {
        case AutoMockable
    }
    
    init(signPost: SignPostProtocol = SignPost.shared, workers: [SourceryWorkerProtocol]? = nil) throws {
        self.signPost = signPost
        
        guard workers == nil else {
            self.workers = workers!
            return
        }
        
        let currentFolder = FileSystem().currentFolder
        signPost.verbose("💁🏻‍♂️ Running in folder\n \(currentFolder)\n")
        
        var carthageFolder: FolderProtocol!
        var projectFolder = try currentFolder.parentFolder().parentFolder().parentFolder()
        
        do {
            signPost.verbose("💁🏻‍♂️ Project in folder\n \(projectFolder.path)\n")
            carthageFolder = try projectFolder.subfolder(named: "Carthage")
        } catch {
            signPost.verbose("💁🏻‍♂️ Not running in .build.nosync/Debug folder, trying to run from current folder.")
            projectFolder = currentFolder
            carthageFolder = try currentFolder.subfolder(named: "Carthage")
        }
        
        let sourcesFolder = try projectFolder.subfolder(named: "Sources")
        let templateFolder = try Folder(relativePath: "Checkouts/template-sourcery/sources/stencil", to: carthageFolder)
        let sourceryAutoProtocolFile = try projectFolder.file(named: "/Sources/AutoGeneratedCode/SourceryAutoProtocols.swift")
        let autoGeneratedCodeFolder = try sourcesFolder.createSubfolderIfNeeded(withName: "AutoGeneratedCode")
        
        let sourcerySequence = try Target.allCases.map { target in
            return try Sourcery(
                sourcesFolders: [sourcesFolder.subfolder(named: target.rawValue)],
                individualSourceFiles: nil,
                templateFolder: templateFolder,
                outputFolder: try autoGeneratedCodeFolder.createSubfolderIfNeeded(withName: target.rawValue),
                sourceryAutoProtocolsFile: sourceryAutoProtocolFile,
                sourceryYMLFile: try projectFolder.createFileIfNeeded(named: ".sourcery-\(target.rawValue).yml"),
                imports: target.imports()
            )
        }
        
        signPost.message("🧙‍♂️ Sourcery will run from config files ...")
        try sourcerySequence.forEach {
            signPost.verbose("""
                > \($0.sourceryYMLFile.path)
                
                ```yml
                \(try $0.sourceryYMLFile.readAsString())
                ```
                
                """
            )
        }
        
        
        self.workers =  try sourcerySequence.map { try SourceryWorker(sourcery: $0) }
        
    }
    
    // MARK: - Sourcery Setup
    
    
    
    func attempt() throws {
        return try workers.forEach {
            let output = try $0.attempt()
            signPost.verbose("\(output.joined(separator: "\n"))")
        }
    }
}
