//
//  SwiftformatWorkerTests.swift
//  SwiftformatWorkerTests
//
//  Created by Stijn on 03/01/2019.
//

import Nimble
import Quick

import SwiftFormatWorker
import ZFile
import ZFileMock
import ProjectFolderWorker

class SwiftformatWorkerTests: QuickSpec
{
    override func spec()
    {
        super.spec()

        context("swiftformat for sources") {
            
            it("does not throw on init")
            {
                expect { try SwiftFormatWorker(forSources: ProjectFolderWorker.self) }.toNot(throwError())
            }
        }
        
        context("swiftformat for auto generated code") {
            
            it("does not throw on init")
            {
                expect { try SwiftFormatWorker(forAutogeneratedCode: ProjectFolderWorker.self) }.toNot(throwError())
            }
        }
        
    }
}
