//
//  SwiftFormatWorker.swift
//  SwiftFormatWorker
//
//  Created by Stijn on 03/01/2019.
//

import os
import ProjectFolderWorker
import SignPost
import SourceryAutoProtocols
import SwiftFormat
import ZFile

public protocol SwiftFormatWorkerProtocol: AutoMockable
{
    /// sourcery:inline:SwiftFormatWorker.AutoGenerateProtocol

    func attempt(_ async: (@escaping (@escaping SwiftFormatWorker.SyncOutput) -> Void))
    /// sourcery:end
}

public class SwiftFormatWorker: SwiftFormatWorkerProtocol, AutoGenerateProtocol
{
    public static let queue: DispatchQueue = DispatchQueue(label: "be.dooz.swiftFormat")
    
    public typealias SyncOutput = () throws -> Void

    public let queue: DispatchQueue

    // MARK: - Private

    private let folderToFormat: FolderProtocol
    private let configFile: FileProtocol
    private let signPost: SignPostProtocol

    // MARK: - Init

    public init(
        forAutogeneratedCode
        projectFolderWorkerType: ProjectFolderWorkerProtocol.Type,
        queue: DispatchQueue = SwiftFormatWorker.queue,
        signPost: SignPostProtocol = SignPost.shared
    ) throws
    {
        self.queue = queue
        self.signPost = signPost

        var folderToFormat: FolderProtocol!
        var currentFolder: FolderProtocol = FileSystem.shared.currentFolder


        signPost.verbose("👨🏻‍🏫 Running in init in folder\n\(currentFolder.name)\n")
        do
        {
            folderToFormat = try currentFolder.subfolder(named: "Sources/AutoGeneratedCode")
        }
        catch
        {
            signPost.verbose("👨🏻‍🏫 ⚠️ Failed to run from current folder at\(FileSystem.shared.currentFolder.path) ⚠️")
            signPost.verbose("👨🏻‍🏫 Will try to run from folder defined in Info.plist with key \(ProjectFolderWorker.Key.scrRoot.rawValue) ...")

            currentFolder = try projectFolderWorkerType.init(bundle: Bundle.main).srcRoot.folder
            folderToFormat = try currentFolder.subfolder(named: "Sources/AutoGeneratedCode")
        }

        configFile = try folderToFormat.file(named: ".swiftformat.md")
        self.folderToFormat = folderToFormat
    }

    public init(
        forSources
        projectFolderWorkerType: ProjectFolderWorkerProtocol.Type,
        queue: DispatchQueue = DispatchQueue(label: "be.dooz.swiftFormat"),
        signPost: SignPostProtocol = SignPost.shared
    ) throws
    {
        self.queue = queue
        self.signPost = signPost

        var folderToFormat: FolderProtocol!
        var currentFolder: FolderProtocol = FileSystem.shared.currentFolder

        signPost.verbose("👨🏻‍🏫 swiftformate init ...")

        signPost.verbose("👨🏻‍🏫 Running in current folder\n\(currentFolder)\n, If this is not the correct folder run AutomateZFile from the folder you want.\n AutomateZFile cannot work for derived data folder.")
        do
        {
            folderToFormat = try currentFolder.subfolder(named: "Sources")
        }
        catch
        {
            signPost.verbose("👨🏻‍🏫 ⚠️ Failed to run from current folder at\(FileSystem.shared.currentFolder.path) ⚠️")
            signPost.verbose("👨🏻‍🏫 Will try to run from folder defined in Info.plist with key \(ProjectFolderWorker.Key.scrRoot.rawValue) ...")

            currentFolder = try projectFolderWorkerType.init(bundle: Bundle.main).srcRoot.folder
            folderToFormat = try currentFolder.subfolder(named: "Sources")
        }

        configFile = try currentFolder.file(named: ".swiftformat.md")
        self.folderToFormat = folderToFormat
    }

    public func attempt(_ asyncSwiftFormatAttemptOutput: (@escaping (@escaping SwiftFormatWorker.SyncOutput) -> Void))
    {
        queue.async
        { [weak self] in
            guard let `self` = self else { return }
           
            self.signPost.verbose("👨🏻‍🏫 \(self.folderToFormat.name) attempt ...")

            CLI.print = { message, type in
                switch type {
                case .info, .success, .content:
                    self.signPost.message("👨🏻‍🏫 \(self.folderToFormat.name) \n\(message)\n")
                case .error:
                    asyncSwiftFormatAttemptOutput { throw Error.cliError("🌋 \n\(message)\n") }
                    break
                case .warning:
                    self.signPost.message("⚠️ \n\(message)\n")
                }
            }

            let arguments = ["", self.folderToFormat.path, "--config", self.configFile.path]
            let output = CLI.run(in: self.folderToFormat.path, with: arguments)

            switch output {
            case .ok:
                asyncSwiftFormatAttemptOutput { return }
            case .lintFailure, .error:
                asyncSwiftFormatAttemptOutput { throw Error.cliError("\(output)") }
                break
            }
        }
    }

    // MARK: - Error

    enum Error: Swift.Error, Equatable
    {
        case cliError(String)
    }
}
