//
//  HighwaySourceryWorker.swift
//  Automate
//
//  Created by Stijn on 16/12/2018.
//

import Foundation
import SourceryAutoProtocols
import SourceryWorker
import os
import ZFile
import Terminal

protocol AutomateSourceryWorkerProtocol: AutoMockable {
    /// sourcery:inline:AutomateSourceryWorker.AutoGenerateProtocol

    func attempt() throws -> [String]
    /// sourcery:end
}

struct AutomateSourceryWorker: AutomateSourceryWorkerProtocol, AutoGenerateProtocol {
    
    private let worker: SourceryWorkerProtocol
    private let signpost: HighwaySignpostProtocol
    
    init(worker: SourceryWorkerProtocol? = nil, signpost: HighwaySignpostProtocol = HighwaySignpost.shared) throws {
        self.signpost = signpost
        
        guard worker == nil else {
            self.worker = worker!
            return
        }
        
        let currentFolder = FileSystem().currentFolder
        signpost.log("💁🏻‍♂️ Running in folder\n \(currentFolder)\n")
        
        let projectFolder = try currentFolder.parentFolder().parentFolder()
        let carthageFolder = try projectFolder.subfolder(named: "Carthage")
        
        let sourcesFolders = try projectFolder.subfolder(named: "Sources")
        signpost.log("💁🏻‍♂️ Sources are in folder\n \(sourcesFolders)\n")
        
        let sourcery = try Sourcery(
            sourcesFolders: sourcesFolders,
            templateFolder: try Folder(relativePath: "Checkouts/template-sourcery/sources/stencil", to: carthageFolder),
            outputFolder: try sourcesFolders.subfolder(named: "AutoGeneratedCode"),
            sourceryAutoProtocolsFile: try sourcesFolders.file(named: "AutoGeneratedCode/SourceryAutoProtocols.swift"),
            sourceryYMLFile: try projectFolder.createFileIfNeeded(named: ".sourcery.yml")
        )
        
        self.worker = try SourceryWorker(sourcery: sourcery)
    }

    func attempt() throws -> [String] {
        return try worker.attempt()
    }
}
